In [3]:
import numpy as np
neuron = 4

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        print('inputs \n' , self.input)
        print()
        self.weights1   = np.random.rand(self.input.shape[1],neuron) 
        print('weights1 \n',self.weights1)
        print()
        self.weights2   = np.random.rand(neuron,1)                 
        print('weights2 \n',self.weights2)
        print()
        self.y          = y
        print('y \n',self.y)
        print()
        self.output     = np.zeros(self.y.shape) # y hat
        print('output \n',self.output)
        print()
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))      
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        
        d_weights1 = np.dot(self.input.T,
                            (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                                    self.weights2.T) * sigmoid_derivative(self.layer1)))
        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2



In [4]:
#x1,x2,x3 and m=4
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

    
nn = NeuralNetwork(X,y)

for i in range(20000):
    nn.feedforward()
    nn.backprop()
print(nn.output)




inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.05371189 0.3755466  0.01504551 0.56272036]
 [0.7191398  0.58287035 0.66892958 0.20924453]
 [0.88577853 0.14388606 0.14497213 0.27952556]]

weights2 
 [[0.88371791]
 [0.61239063]
 [0.13234665]
 [0.54922119]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

[[0.00181654]
 [0.99323029]
 [0.99329291]
 [0.00835314]]
